/* 
 * This file is the part of project CodeBuilder which is 
 * created for the creating NesC files (C and AppC) using 
 * graphics interface.
 *
 * Author : Trusit Shah
 * Date : 16-07-2014
 * 
 */

package CodeBuilder.Objects;

/**
 * This class represents the function element in C file.
 * These are the events generated by the interfaces used by object.
 * 
 * @author trusit
 *
 */
public class Function 
{
	/**
	 * Prototype of function.
	 */
	private String Prototype;
	
	/**
	 * 
	 * @param Prototype prototype of function
	 */
	public Function(String Prototype)
	{
		this.Prototype = Prototype;
	}
	
	/**
	 * 
	 * @return Prototype of function
	 */
	public String GetPrototype()
	{
		return Prototype;
	}
	
}
